"""initial migration

Revision ID: aa72573e0e62
Revises: 
Create Date: 2025-11-17 16:34:41.368907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa72573e0e62'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_id'), 'clinic', ['id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('doctor',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('qualifications', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('about', sa.String(length=500), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected', name='verificationenum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_doctor_clinic_id'), 'doctor', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_doctor_user_id'), 'doctor', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('bloodGroup', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('clinic_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_start', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('scheduled_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('appointment_status', sa.Enum('PENDING', 'APPROVED', 'CANCELLED', 'IN_PROGRESS', 'COMPLETED', 'RESCHEDULED', name='appointmentstatus'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['patients.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_clinic_id'), 'appointment', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_appointment_doctor_id'), 'appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointment_id'), 'appointment', ['id'], unique=False)
    op.create_index(op.f('ix_appointment_user_id'), 'appointment', ['user_id'], unique=False)
    op.create_table('assistant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('appointed_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['patients.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_doctor_id'), 'assistant', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_assistant_id'), 'assistant', ['id'], unique=False)
    op.create_index(op.f('ix_assistant_user_id'), 'assistant', ['user_id'], unique=False)
    op.create_table('doctor_verification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('DegreePath', sa.String(length=250), nullable=False),
    sa.Column('nationalCardFront', sa.String(length=250), nullable=False),
    sa.Column('nationalCardBack', sa.String(length=250), nullable=False),
    sa.Column('doctorCard', sa.String(length=250), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='statusenum'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_verification_doctor_id'), 'doctor_verification', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_verification_id'), 'doctor_verification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_verification_id'), table_name='doctor_verification')
    op.drop_index(op.f('ix_doctor_verification_doctor_id'), table_name='doctor_verification')
    op.drop_table('doctor_verification')
    op.drop_index(op.f('ix_assistant_user_id'), table_name='assistant')
    op.drop_index(op.f('ix_assistant_id'), table_name='assistant')
    op.drop_index(op.f('ix_assistant_doctor_id'), table_name='assistant')
    op.drop_table('assistant')
    op.drop_index(op.f('ix_appointment_user_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_doctor_id'), table_name='appointment')
    op.drop_index(op.f('ix_appointment_clinic_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctor_user_id'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_clinic_id'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('role')
    op.drop_index(op.f('ix_clinic_id'), table_name='clinic')
    op.drop_table('clinic')
    # ### end Alembic commands ###
